### ISSUE TITLE
No output from command

### ISSUE THREAD

**Issue by springjools** [rickhousley/creepr#2]
I'm new to python, so maybe I'm doing something wrong, but I get no output from the command at all. Like this:
![bug](https://cloud.githubusercontent.com/assets/5911982/13373075/d03d4050-dd65-11e5-8a26-cb25e98b8473.png)

**Comment by rickhousley** [comment]
I haven't taken at the code in a while, but I intentionally left the uploaded version a little unfinished due to the nature of what it can doe. Sorry! If you're looking to emulate it take a look at enumUsers.

**Comment by springjools** [comment]
Hey, you're right of course, with great powers cometh great responsibility. But on the other hand, this issue is there already be the design of this app (you can trilaterate manually if you really wish), and is there because people probably don't realise the consequences of what they are sharing. So this program would serve a good purpose for raising awareness.
